global:
  smtp_smarthost: 'smtp.163.com:25'
  smtp_from: 'xx@xx.com'
  smtp_auth_username: 'xx@xx.com'
  smtp_auth_password: 'xx'
  smtp_require_tls: false
  wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  wechat_api_secret: 'xx'
  wechat_api_corp_id: 'xx'

templates:
  - '/srv/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname','cluster','service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: 'wechat'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'xx@xx.com'
    send_resolved: true
    html: '{{ template "email.default.html" . }}'
    headers: { Subject: "Prometheus 报警邮件" }
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    to_party: '1'
    agent_id: '1000006'
    corp_id: 'xx'
    api_secret: 'xx'
